### ISSUE TITLE
Label CSS

### ISSUE THREAD

**Issue by headzoo** [DeskproApps/deskpro-components#36]
I tried using the `Forms/Label` component in a form, but noticed the default CSS puts the labels inside of a grey box. Can we remove that styling? The grey box seems to exist to serve some specific purpose, but _most_ labels won't be shown inside of grey boxes. It seems the default label component should have only a minimum of styling. Otherwise we're going to end up writing a lot of boilerplate CSS to remove those default styles every time we use a label.

**Comment by jducro** [comment]
Labels is the terminology we use for Tags here, so I used InputLabel for the <label> instead.

We should probably rename Labels to Tags as a Component to avoid this confusion

**Comment by headzoo** [comment]
> We should probably rename Labels to Tags as a Component to avoid this confusion

That might work best since "label" is such a simple term with so many meanings, that it should remain a fairly generic component. You could fiddle around with the namespace instead of changing the name of the component. Having `Label` in the `Forms` namespace is the only thing making the component name confusing.

**Comment by jducro** [comment]
Fixed
