### ISSUE TITLE
Namespacing the components

### ISSUE THREAD

**Issue by headzoo** [DeskproApps/deskpro-components#4]
I wanted to get feedback on the idea of namespacing the components, which I think will help organize them as the project grows.

For example, instead of having this:

* Components/Input.js
* Components/InputLabel.js
* Components/Label.js
* Components/LabelInput.js
* Components/LabelInputAutosuggest.js

We would have something like this:

* Components/Forms/Input.js
* Components/Forms/InputLabel.js
* Components/Forms/Label.js
* Components/Forms/LabelInput.js
* Components/Forms/InputAutosuggest.js

**Comment by jducro** [comment]
I quite like the idea to keep things tidy and avoid having a massive folder with everything.

And we should definitely do it before having to change to many thing in the main code.

**Comment by headzoo** [comment]
@jducro I'll follow your lead since you created the current set of components.

Some random thoughts I have on the matter:

* Components like `List` and `ListElement` could go into a `Components/Common` namespace, since we're likely to use them at the core of other components.

* We could add an `index.js` to each namespace to make it easier to import the components. For example, given the following components:

  * Components/Forms/Input.js
  * Components/Forms/InputLabel.js

We could create (or auto-generate) `Components/Forms/index.js` which simply has the following:

```js
import Input from 'Components/Forms/Input';
import InputLabel from 'Components/Forms/InputLabel';

export Input;
export InputLabel;
```

From other components the `Components/Forms` namespace could be used like this:

```js
import { Input, InputLabel } from 'Components/Forms';
```

Or even like this:

```js
import * as Forms from `Component/Forms`;

const MyForm = () => (
  <div>
     <form>
       <Forms.Input />
     </form>
  </div>
);
```

That approach will make it easier to write import statements when a lot of components are needed from a specific namespace.

**Comment by jducro** [comment]
Done in #5

**Comment by chroder** [comment]
Is this issue closed then?
