### ISSUE TITLE
Switch to .jsx file extension

### ISSUE THREAD

**Issue by headzoo** [DeskproApps/deskpro-components#6]
Thoughts on using .jsx instead of .js for components? I see .jsx is being used for the Storybook tests. It might make sense to use .jsx for the components as well in order to be consistent.

**Comment by jducro** [comment]
Agreed, we already talked about it with @chroder

**Comment by chroder** [comment]
Yeah, Julien brought this up a few weeks ago. I think we should too.

Go for it!

**Comment by headzoo** [comment]
I'll make these changes. Waiting to see if my [current pull request](https://github.com/DeskproApps/deskpro-components/pull/7) can get merged first.
